pipeline:
  name: SCC GenAI Demo
  identifier: SCC_GenAI_Demo
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: githubconnectorpersonal
        repoName: scc-preventive-demo
        build: <+input>
  stages:
    - stage:
        name: Preventive Workflow
        identifier: Checkout
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: kubernetesclusterscc
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: List all files
                  identifier: List_all_files
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform
                    shell: Sh
                    command: ls -al
              - step:
                  type: Run
                  name: terraform init
                  identifier: terraform_init
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform
                    shell: Sh
                    command: terraform init
              - step:
                  type: Run
                  name: terraform plan
                  identifier: terraform_plan
                  spec:
                    connectorRef: account.harnessImage
                    image: hashicorp/terraform
                    shell: Sh
                    command: |-
                      terraform plan -out=main-plan
                      terraform show -json main-plan > plan.json
                      cat plan.json
              - step:
                  type: Run
                  name: Security Posture Validation
                  identifier: Security_Posture_Validation
                  spec:
                    connectorRef: account.harnessImage
                    image: google/cloud-sdk
                    shell: Sh
                    command: "curl -m 70 -X POST https://europe-west2-sec-scc-tst.cloudfunctions.net/handle-scc-findings-from-psb \\-H \"Authorization: bearer $(gcloud auth print-identity-token)\" \\-H \"Content-Type: application/json\" \\-H \"ce-id: 1234567890\" \\-H \"ce-specversion: 1.0\" \\-H \"ce-type: google.cloud.pubsub.topic.v1.messagePublished\" \\-H \"ce-time: 2020-08-08T00:11:44.895529672Z\" \\-H \"ce-source: //pubsub.googleapis.com/projects/sec-scc-tst/topics/scc-finding\" \\-d '{  \"message\": {    \"_comment\": \"IAC\",    \"data\": {\"format_version\":\"1.2\",\"terraform_version\":\"1.5.7\",\"planned_values\":{\"root_module\":{\"resources\":[{\"address\":\"google_storage_bucket.example_bucket\",\"mode\":\"managed\",\"type\":\"google_storage_bucket\",\"name\":\"example_bucket\",\"provider_name\":\"registry.terraform.io/hashicorp/google\",\"schema_version\":1,\"values\":{\"autoclass\":[],\"cors\":[],\"custom_placement_config\":[],\"default_event_based_hold\":null,\"enable_object_retention\":null,\"encryption\":[],\"force_destroy\":true,\"labels\":null,\"lifecycle_rule\":[],\"location\":\"EU\",\"logging\":[],\"name\":\"example-bucket-1\",\"project\":\"sec-scc-tst\",\"requester_pays\":null,\"retention_policy\":[],\"storage_class\":\"STANDARD\",\"timeouts\":null,\"uniform_bucket_level_access\":false,\"versioning\":[{\"enabled\":false}]},\"sensitive_values\":{\"autoclass\":[],\"cors\":[],\"custom_placement_config\":[],\"effective_labels\":{},\"encryption\":[],\"lifecycle_rule\":[],\"logging\":[],\"retention_policy\":[],\"soft_delete_policy\":[],\"terraform_labels\":{},\"versioning\":[{}],\"website\":[]}}]}},\"resource_changes\":[{\"address\":\"google_storage_bucket.example_bucket\",\"mode\":\"managed\",\"type\":\"google_storage_bucket\",\"name\":\"example_bucket\",\"provider_name\":\"registry.terraform.io/hashicorp/google\",\"change\":{\"actions\":[\"create\"],\"before\":null,\"after\":{\"autoclass\":[],\"cors\":[],\"custom_placement_config\":[],\"default_event_based_hold\":null,\"enable_object_retention\":null,\"encryption\":[],\"force_destroy\":true,\"labels\":null,\"lifecycle_rule\":[],\"location\":\"EU\",\"logging\":[],\"name\":\"example-bucket-1\",\"project\":\"sec-scc-tst\",\"requester_pays\":null,\"retention_policy\":[],\"storage_class\":\"STANDARD\",\"timeouts\":null,\"uniform_bucket_level_access\":false,\"versioning\":[{\"enabled\":false}]},\"after_unknown\":{\"autoclass\":[],\"cors\":[],\"custom_placement_config\":[],\"effective_labels\":true,\"encryption\":[],\"id\":true,\"lifecycle_rule\":[],\"logging\":[],\"project_number\":true,\"public_access_prevention\":true,\"retention_policy\":[],\"rpo\":true,\"self_link\":true,\"soft_delete_policy\":true,\"terraform_labels\":true,\"url\":true,\"versioning\":[{}],\"website\":true},\"before_sensitive\":false,\"after_sensitive\":{\"autoclass\":[],\"cors\":[],\"custom_placement_config\":[],\"effective_labels\":{},\"encryption\":[],\"lifecycle_rule\":[],\"logging\":[],\"retention_policy\":[],\"soft_delete_policy\":[],\"terraform_labels\":{},\"versioning\":[{}],\"website\":[]}}}],\"configuration\":{\"provider_config\":{\"google\":{\"name\":\"google\",\"full_name\":\"registry.terraform.io/hashicorp/google\",\"expressions\":{\"project\":{\"constant_value\":\"sec-scc-tst\"},\"region\":{\"constant_value\":\"europe-west1\"},\"zone\":{\"constant_value\":\"europe-west1-b\"}}}},\"root_module\":{\"resources\":[{\"address\":\"google_storage_bucket.example_bucket\",\"mode\":\"managed\",\"type\":\"google_storage_bucket\",\"name\":\"example_bucket\",\"provider_config_key\":\"google\",\"expressions\":{\"force_destroy\":{\"constant_value\":true},\"location\":{\"constant_value\":\"EU\"},\"name\":{\"constant_value\":\"example-bucket-1\"},\"project\":{\"constant_value\":\"sec-scc-tst\"},\"uniform_bucket_level_access\":{\"constant_value\":false},\"versioning\":[{\"enabled\":{\"constant_value\":false}}]},\"schema_version\":1}]}},\"timestamp\":\"2024-06-28T10:22:59Z\"}  }}'"
                  timeout: 10m
          caching:
            enabled: true
            paths: []
